name: Update Domain List

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Allows manual trigger

jobs:
  update-domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and format domain list
      run: |
        # Download the original list
        curl -sL https://www.usom.gov.tr/url-list.txt -o raw.txt

        # Prepend '||' and append '^' to each line
        awk '{print "||"$0"^"}' raw.txt > domains.txt

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add domains.txt
        git commit -m "Automatically updated domain list"
        git push
